// packages/svelte/src/lib/BabloomEditor.svelte
<script lang="ts">
  import { Editor, type EditorOptions } from "@tlob/babloom-core";
  import { onDestroy, onMount } from "svelte";

  export let options: Omit<EditorOptions, "element"> = {};
  export let editor: Editor | null = null;
  let element: HTMLDivElement;

  onMount(() => {
    editor = new Editor({ ...options, element });
  });

  onDestroy(() => {
    editor?.destroy();
    editor = null;
  });
</script>

<div bind:this={element} class={$$props.class}></div>

// packages/vue/src/BabloomEditor.vue
<script setup lang="ts">
import type { EditorOptions } from "@tlob/babloom-core";
import { useEditor } from "./useEditor";

const props = defineProps<{ options?: Omit<EditorOptions, "element">; class?: string }>();
const { editor, element } = useEditor(props.options ?? {});
defineExpose({ editor });
</script>

<template>
  <div ref="element" :class="props.class" />
</template>
